{{- $name := coalesce .Values.destinationRule.name .Values.serviceProperties.name -}}
{{- $namespace := coalesce .Values.destinationRule.namespace .Values.serviceProperties.namespace -}}
{{- $enabled := .Values.destinationRule.enabled -}}

{{ if $enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  host: {{ coalesce .Values.destinationRule.host .Values.serviceProperties.name }}
  trafficPolicy:
    loadBalancer:
      simple: {{ .Values.destinationRule.trafficPolicy.loadBalancer.simple | upper }}
    {{- if .Values.destinationRule.trafficPolicy.tls }}
    tls:
      mode: {{ .Values.destinationRule.trafficPolicy.tls.mode | upper }}
    {{- end }}
    {{ if and .Values.destinationRule.portLevelSettings (not (empty .Values.destinationRule.portLevelSettings )) }}
    portLevelSettings:
      {{ range .Values.destinationRule.portLevelSettings }}
      - port:
          number: {{ .port.number }}
        loadBalancer:
          simple: {{ .loadBalancer.simple | upper }}
      {{- end }}
    {{- end }}
    {{ if .Values.destinationRule.subsets}}
    subsets:
      {{ range .Values.destinationRule.subsets }}
      - name: {{ .name }}
        labels:
          version: {{ .labels.version }}
        trafficPolicy:
          loadBalancer:
            simple: {{ .trafficPolicy.loadBalancer.simple | upper }}
      {{- end }}
    {{- end }}
{{- end }}